### ISSUE TITLE
Add static assets

### ISSUE THREAD

**Issue by dhillonks** [dhillonks/cli-ssg#22]
## Description
We should add the ability to provide assets in generated websites through a directory called `static` in the project root. Everything that the user puts in this directory should be copied into the root of the generated build folder with the directory hierarchy preserved. The user should also be able to specify a base URL which can be used to reference content.
For example:
- if `baseUrl: '/'`, then the image `/static/img/cat.png` will be served at `/static/img/cat.png`
- if `baseUrl: '/home'`, then the image `/static/img/cat.png` will be served at `/home/img/cat.png`

## To-do
- [ ] User can provide assets through `static` directory
- [ ] Assets can be of the type: `images, stylesheets, favicons`
- [ ] The user should have the option to specify a base URL, defaulting to `'/'`
